name: appsync_subscription
description: A plugin abstract subscribe to AppSync subscription topics.
repository: https://github.com/mhd999/appsync-subscription

version: 1.0.2

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  http: 0.13.0
  mqtt_client: ^8.1.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
